package dotenv

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/montanaflynn/envc/internal/destination"
)

func TestParseConfig(t *testing.T) {
	tests := []struct {
		name    string
		raw     map[string]any
		want    Config
		wantErr string
	}{
		{name: "nil → defaults", raw: nil, want: Config{Path: ".env", Override: ".env.local"}},
		{name: "empty → defaults", raw: map[string]any{}, want: Config{Path: ".env", Override: ".env.local"}},
		{name: "explicit", raw: map[string]any{"path": "web/.env", "override": "web/.env.local"}, want: Config{Path: "web/.env", Override: "web/.env.local"}},
		{name: "path only", raw: map[string]any{"path": "x.env"}, want: Config{Path: "x.env", Override: ".env.local"}},
		{name: "unknown field", raw: map[string]any{"paht": ".env"}, wantErr: `unknown field "paht"`},
		{name: "wrong type", raw: map[string]any{"path": 3}, wantErr: `"path" must be a string`},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, err := ParseConfig(tc.raw)
			if tc.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tc.wantErr) {
					t.Fatalf("err = %v, want containing %q", err, tc.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if got != tc.want {
				t.Fatalf("got %+v, want %+v", got, tc.want)
			}
		})
	}
}

func newDest(t *testing.T, root string, raw map[string]any) destination.Destination {
	t.Helper()
	d, err := destination.New(Name, destination.Env{Root: root, Env: "local", Getenv: func(string) string { return "" }, Log: &bytes.Buffer{}}, raw)
	if err != nil {
		t.Fatal(err)
	}
	if d.Name() != Name {
		t.Fatalf("Name() = %q", d.Name())
	}
	if sr, ok := d.(destination.SecretReader); !ok || !sr.ReadsBackSecrets() {
		t.Fatal("dotenv must report ReadsBackSecrets() == true")
	}
	return d
}

func TestLive(t *testing.T) {
	root := t.TempDir()
	d := newDest(t, root, nil)

	// Missing file → empty snapshot, no error.
	got, err := d.Live(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("Live on missing file = %v, want empty", got)
	}

	if err := os.WriteFile(filepath.Join(root, ".env"), []byte("# comment\nA=1\nB=\"two words\"\nexport C=x\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err = d.Live(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	want := destination.Snapshot{"A": {Value: "1"}, "B": {Value: "two words"}, "C": {Value: "x"}}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("Live = %v, want %v", got, want)
	}
}

func TestApply(t *testing.T) {
	tests := []struct {
		name     string
		existing string // "" = no file
		want     destination.Snapshot
		opts     destination.ApplyOptions
		report   destination.Report
		wantFile string // "" = must not exist
	}{
		{
			name:     "create from nothing",
			want:     destination.Snapshot{"B": {Value: "2", Secret: true}, "A": {Value: "1"}},
			report:   destination.Report{Created: []string{"A", "B"}},
			wantFile: "# generated by envc — do not edit; put overrides in .env.local\nA=1\nB=2\n",
		},
		{
			name:     "update, unchanged, prune always",
			existing: "A=old\nB=2\nGONE=x\n",
			want:     destination.Snapshot{"A": {Value: "new"}, "B": {Value: "2"}, "C": {Value: "3"}},
			report:   destination.Report{Created: []string{"C"}, Updated: []string{"A"}, Unchanged: []string{"B"}, Pruned: []string{"GONE"}},
			wantFile: "# generated by envc — do not edit; put overrides in .env.local\nA=new\nB=2\nC=3\n",
		},
		{
			name:     "prune reported even with Prune=true",
			existing: "GONE=x\n",
			want:     destination.Snapshot{},
			opts:     destination.ApplyOptions{Prune: true},
			report:   destination.Report{Pruned: []string{"GONE"}},
			wantFile: "# generated by envc — do not edit; put overrides in .env.local\n",
		},
		{
			name:     "dry run writes nothing",
			existing: "A=old\n",
			want:     destination.Snapshot{"A": {Value: "new"}, "N": {Value: "1"}},
			opts:     destination.ApplyOptions{DryRun: true},
			report:   destination.Report{Created: []string{"N"}, Updated: []string{"A"}},
			wantFile: "A=old\n",
		},
		{
			name:     "dry run on missing file leaves it missing",
			want:     destination.Snapshot{"A": {Value: "1"}},
			opts:     destination.ApplyOptions{DryRun: true},
			report:   destination.Report{Created: []string{"A"}},
			wantFile: "",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			path := filepath.Join(root, ".env")
			if tc.existing != "" {
				if err := os.WriteFile(path, []byte(tc.existing), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			d := newDest(t, root, nil)
			got, err := d.Apply(context.Background(), tc.want, tc.opts)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(norm(got), norm(tc.report)) {
				t.Fatalf("report = %+v, want %+v", got, tc.report)
			}
			data, err := os.ReadFile(path)
			if tc.wantFile == "" {
				if err == nil {
					t.Fatalf("file exists with %q, want absent", data)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if string(data) != tc.wantFile {
				t.Fatalf("file =\n%s\nwant\n%s", data, tc.wantFile)
			}
			if !tc.opts.DryRun {
				st, _ := os.Stat(path)
				if st.Mode().Perm() != 0o600 {
					t.Fatalf("mode = %o, want 0600", st.Mode().Perm())
				}
			}
			// Round-trip: Live after Apply equals want with Secret cleared.
			if tc.opts.DryRun {
				return
			}
			live, err := d.Live(context.Background())
			if err != nil {
				t.Fatal(err)
			}
			exp := destination.Snapshot{}
			for k, e := range tc.want {
				exp[k] = destination.Entry{Value: e.Value}
			}
			if !reflect.DeepEqual(live, exp) {
				t.Fatalf("Live after Apply = %v, want %v", live, exp)
			}
		})
	}
}

func TestApplyCustomPathsAndHeader(t *testing.T) {
	root := t.TempDir()
	d := newDest(t, root, map[string]any{"path": "web/.env", "override": "web/.env.local"})
	rep, err := d.Apply(context.Background(), destination.Snapshot{"K": {Value: "a b"}}, destination.ApplyOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(rep.Created, []string{"K"}) {
		t.Fatalf("report = %+v", rep)
	}
	data, err := os.ReadFile(filepath.Join(root, "web", ".env"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# generated by envc — do not edit; put overrides in web/.env.local\nK=\"a b\"\n"
	if string(data) != want {
		t.Fatalf("file = %q, want %q", data, want)
	}
	if _, err := os.Stat(filepath.Join(root, "web", ".env.local")); !os.IsNotExist(err) {
		t.Fatal("override file must never be written")
	}
	// No leftover temp files.
	entries, _ := os.ReadDir(filepath.Join(root, "web"))
	if len(entries) != 1 {
		t.Fatalf("leftover files: %v", entries)
	}
}

func TestPaths(t *testing.T) {
	root := t.TempDir()
	d, err := New(destination.Env{Root: root}, map[string]any{"path": ".env", "override": "/abs/.env.local"})
	if err != nil {
		t.Fatal(err)
	}
	de := d.(*Dotenv)
	if got := de.Path(); got != filepath.Join(root, ".env") {
		t.Fatalf("Path() = %q", got)
	}
	if got := de.OverridePath(); got != "/abs/.env.local" {
		t.Fatalf("OverridePath() = %q", got)
	}
}

func norm(r destination.Report) destination.Report {
	fix := func(s []string) []string {
		if len(s) == 0 {
			return nil
		}
		return s
	}
	return destination.Report{Created: fix(r.Created), Updated: fix(r.Updated), Unchanged: fix(r.Unchanged), Pruned: fix(r.Pruned), Skipped: fix(r.Skipped)}
}
