// Package dotenv writes a generated .env file. It never touches the override
// file (.env.local); that path is exposed so `envc run` can layer it.
//
// The file is regenerated wholesale on every Apply, so a key that is present
// in the file but absent from the resolved values is always removed; it is reported
// under Report.Pruned whether or not ApplyOptions.Prune is set. Live reports
// every entry as Secret: false because a .env file cannot say otherwise, but
// the values are readable, so ReadsBackSecrets is true.
package dotenv

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/montanaflynn/envc/internal/destination"
	"github.com/montanaflynn/envc/internal/resolve"
)

const Name = "dotenv"

// Config is sync.<env>.dotenv.
type Config struct {
	Path     string `yaml:"path"`               // default ".env"
	Override string `yaml:"override,omitempty"` // default ".env.local"; never written
}

// ParseConfig decodes the raw block with defaults applied.
func ParseConfig(raw map[string]any) (Config, error) {
	cfg := Config{Path: ".env", Override: ".env.local"}
	for k, v := range raw {
		s, ok := v.(string)
		if !ok && v != nil {
			return Config{}, fmt.Errorf("dotenv: %q must be a string", k)
		}
		switch k {
		case "path":
			if s != "" {
				cfg.Path = s
			}
		case "override":
			if s != "" {
				cfg.Override = s
			}
		default:
			return Config{}, fmt.Errorf("dotenv: unknown field %q (allowed: path, override)", k)
		}
	}
	return cfg, nil
}

// Dotenv is the destination. Config paths are relative to Root unless absolute.
type Dotenv struct {
	Config Config
	Root   string
}

// New builds the destination. Registered under Name in init().
func New(env destination.Env, raw map[string]any) (destination.Destination, error) {
	cfg, err := ParseConfig(raw)
	if err != nil {
		return nil, err
	}
	return &Dotenv{Config: cfg, Root: env.Root}, nil
}

func init() { destination.Register(Name, New) }

// Name implements destination.Destination.
func (d *Dotenv) Name() string { return Name }

// ReadsBackSecrets implements destination.SecretReader: a file returns every
// value it holds.
func (d *Dotenv) ReadsBackSecrets() bool { return true }

// Path is the absolute path of the generated file.
func (d *Dotenv) Path() string { return d.abs(d.Config.Path) }

// OverridePath is the absolute path of the hand-maintained override file.
// envc never writes it.
func (d *Dotenv) OverridePath() string { return d.abs(d.Config.Override) }

func (d *Dotenv) abs(p string) string {
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(d.Root, p)
}

// Live parses the generated file. A missing file is an empty snapshot.
func (d *Dotenv) Live(ctx context.Context) (destination.Snapshot, error) {
	data, err := os.ReadFile(d.Path())
	if errors.Is(err, os.ErrNotExist) {
		return destination.Snapshot{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("dotenv: %w", err)
	}
	vars, err := resolve.Parse(string(data))
	if err != nil {
		return nil, fmt.Errorf("dotenv: parse %s: %w", d.Path(), err)
	}
	snap := make(destination.Snapshot, len(vars))
	for k, v := range vars {
		snap[k] = destination.Entry{Value: v}
	}
	return snap, nil
}

// Apply regenerates the file from want. See the package comment for prune
// semantics. DryRun computes the report without writing.
func (d *Dotenv) Apply(ctx context.Context, want destination.Snapshot, opts destination.ApplyOptions) (destination.Report, error) {
	live, err := d.Live(ctx)
	if err != nil {
		return destination.Report{}, err
	}
	var rep destination.Report
	vars := make(resolve.Vars, len(want))
	for k, e := range want {
		vars[k] = e.Value
		cur, ok := live[k]
		switch {
		case !ok:
			rep.Created = append(rep.Created, k)
		case cur.Value == e.Value:
			rep.Unchanged = append(rep.Unchanged, k)
		default:
			rep.Updated = append(rep.Updated, k)
		}
	}
	for k := range live {
		if _, ok := want[k]; !ok {
			rep.Pruned = append(rep.Pruned, k)
		}
	}
	sort.Strings(rep.Created)
	sort.Strings(rep.Updated)
	sort.Strings(rep.Unchanged)
	sort.Strings(rep.Pruned)
	if opts.DryRun {
		return rep, nil
	}
	body := fmt.Sprintf("# generated by envc — do not edit; put overrides in %s\n%s", d.Config.Override, resolve.Encode(vars))
	if err := writeAtomic(d.Path(), []byte(body)); err != nil {
		return destination.Report{}, fmt.Errorf("dotenv: %w", err)
	}
	return rep, nil
}

// writeAtomic writes data to a temp file beside path (mode 0600) and renames
// it into place.
func writeAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		cleanup()
		return err
	}
	return nil
}
